version: '3.1'
services:
  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    env_file:
      - ./bot/.env
    expose:
      - 3000
    restart: always
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:5000"
    env_file:
      - ./server/.env
    expose:
      - 5000